# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hs_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowReturnStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('borrow_count', models.BigIntegerField(default=0)),
                ('return_count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
